export const englishWords = [
  'apple', 'banana', 'orange', 'grape', 'lemon', 'melon', 'peach', 'pear', 'plum', 'berry',
  'carrot', 'potato', 'tomato', 'onion', 'garlic', 'ginger', 'pepper', 'corn', 'bean', 'pea',
  'bread', 'butter', 'cheese', 'cream', 'milk', 'yogurt', 'egg', 'meat', 'fish', 'pork',
  'beef', 'chicken', 'lamb', 'duck', 'goose', 'rice', 'noodle', 'pasta', 'pizza', 'burger',
  'water', 'juice', 'coffee', 'tea', 'soda', 'wine', 'beer', 'coke', 'soup', 'sauce',
  'house', 'home', 'room', 'door', 'window', 'wall', 'floor', 'roof', 'garden', 'yard',
  'table', 'chair', 'sofa', 'bed', 'desk', 'lamp', 'light', 'fan', 'clock', 'watch',
  'book', 'paper', 'pen', 'pencil', 'ruler', 'eraser', 'bag', 'box', 'card', 'gift',
  'phone', 'computer', 'mouse', 'screen', 'keyboard', 'camera', 'radio', 'video', 'music', 'game',
  'happy', 'sad', 'angry', 'tired', 'hungry', 'thirsty', 'busy', 'free', 'cool', 'warm',
  'good', 'bad', 'big', 'small', 'long', 'short', 'tall', 'fat', 'thin', 'fast',
  'slow', 'hot', 'cold', 'wet', 'dry', 'clean', 'dirty', 'new', 'old', 'young',
  'red', 'blue', 'green', 'yellow', 'black', 'white', 'gray', 'brown', 'pink', 'purple',
  'one', 'two', 'three', 'four', 'five', 'six', 'seven', 'eight', 'nine', 'ten',
  'run', 'walk', 'jump', 'swim', 'fly', 'sleep', 'eat', 'drink', 'read', 'write',
  'listen', 'speak', 'sing', 'dance', 'play', 'work', 'study', 'cook', 'wash', 'clean',
  'love', 'like', 'hate', 'want', 'need', 'know', 'think', 'feel', 'see', 'hear',
  'sun', 'moon', 'star', 'sky', 'cloud', 'rain', 'snow', 'wind', 'tree', 'flower',
  'bird', 'cat', 'dog', 'fish', 'horse', 'lion', 'tiger', 'bear', 'wolf', 'monkey',
  'city', 'town', 'village', 'park', 'shop', 'school', 'bank', 'post', 'office', 'hotel',
  'bus', 'car', 'taxi', 'bike', 'train', 'plane', 'ship', 'boat', 'road', 'street',
  'world', 'country', 'state', 'land', 'sea', 'ocean', 'river', 'lake', 'hill', 'mountain',
  'year', 'month', 'week', 'day', 'hour', 'minute', 'second', 'time', 'date', 'morning',
  'noon', 'afternoon', 'evening', 'night', 'today', 'tomorrow', 'yesterday', 'now', 'then', 'later'
];

export const chineseWords = [
  '你好', '世界', '快乐', '幸福', '美丽', '阳光', '月亮', '星星', '天空', '大海',
  '森林', '花朵', '树木', '小草', '春风', '夏雨', '秋叶', '冬雪', '红色', '蓝色',
  '绿色', '黄色', '白色', '黑色', '紫色', '橙色', '粉色', '金色', '银色', '灰色',
  '苹果', '香蕉', '橘子', '葡萄', '西瓜', '草莓', '樱桃', '柠檬', '桃子', '梨子',
  '土豆', '番茄', '黄瓜', '茄子', '辣椒', '洋葱', '大蒜', '生姜', '玉米', '大豆',
  '米饭', '面条', '馒头', '包子', '饺子', '馄饨', '火锅', '烧烤', '汉堡', '披萨',
  '牛奶', '豆浆', '咖啡', '茶水', '果汁', '可乐', '雪碧', '啤酒', '红酒', '白酒',
  '房子', '房间', '客厅', '卧室', '厨房', '厕所', '阳台', '花园', '窗户', '大门',
  '桌子', '椅子', '沙发', '床铺', '书桌', '台灯', '风扇', '空调', '冰箱', '电视',
  '书本', '纸张', '铅笔', '钢笔', '尺子', '橡皮', '书包', '盒子', '卡片', '礼物',
  '手机', '电脑', '鼠标', '键盘', '屏幕', '相机', '广播', '视频', '音乐', '游戏',
  '开心', '难过', '生气', '疲惫', '饥饿', '口渴', '忙碌', '空闲', '凉爽', '温暖',
  '优秀', '糟糕', '巨大', '微小', '漫长', '短暂', '高大', '肥胖', '瘦弱', '快速',
  '缓慢', '炎热', '寒冷', '潮湿', '干燥', '干净', '肮脏', '崭新', '陈旧', '年轻',
  '一', '二', '三', '四', '五', '六', '七', '八', '九', '十',
  '跑步', '行走', '跳跃', '游泳', '飞翔', '睡觉', '吃饭', '喝水', '阅读', '写作',
  '倾听', '说话', '唱歌', '跳舞', '玩耍', '工作', '学习', '做饭', '洗衣', '打扫',
  '喜爱', '喜欢', '讨厌', '想要', '需要', '知道', '思考', '感觉', '看见', '听见',
  '太阳', '月球', '星球', '云朵', '雨滴', '雪花', '微风', '树林', '鲜花', '小鸟',
  '猫咪', '小狗', '金鱼', '骏马', '狮子', '老虎', '黑熊', '野狼', '猴子', '大象',
  '城市', '城镇', '乡村', '公园', '商店', '学校', '银行', '邮局', '公司', '酒店',
  '汽车', '公交', '出租', '单车', '火车', '飞机', '轮船', '小船', '马路', '街道',
  '世界', '国家', '省份', '陆地', '海洋', '江河', '湖泊', '山丘', '高山', '平原',
  '今年', '本月', '本周', '今天', '小时', '分钟', '秒钟', '时间', '日期', '早晨',
  '中午', '下午', '傍晚', '夜晚', '现在', '明天', '昨天', '未来', '过去', '历史'
];
